"""Type-catalog regression tests. Document mode by default; no browser policy changes.
GERBIL_TEST_MODE=http GERBIL_URL=http://127.0.0.1:4173 python tests/browser_test.py
"""
import json,os,shutil
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'qa'; OUT.mkdir(exist_ok=True)
HTML=(ROOT/'Gerbil-Threat-Index-preview.html').read_text()
MODE=os.getenv('GERBIL_TEST_MODE','document');BASE=os.getenv('GERBIL_URL','http://127.0.0.1:4173')
checks=[]; errors=[]; requests=[]
def check(name,value=True):
    assert value,name
    checks.append(name)
def load(page):
    if MODE=='http':
        r=page.goto(BASE);assert r and r.status==200
    else:
        page.goto('about:blank');page.set_content(HTML,wait_until='load')
    expect(page.locator('#watch-rows tr')).to_have_count(10)
def fits(page,name):
    check(name,page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
    if page.locator('#dialog').is_visible():
        check(name+' dialog',page.locator('#dialog').evaluate('(e)=>e.scrollWidth<=e.clientWidth'))
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.getenv('CHROMIUM_PATH') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1050},reduced_motion='reduce',accept_downloads=True)
    page=context.new_page()
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
    page.on('request',lambda r:requests.append(r.url) if not r.url.startswith((BASE,'data:','blob:')) else None)
    load(page)
    check('register lists real types, not fictional pets','Admiral Crumb' not in page.locator('body').inner_text() and page.locator('#watch-rows strong').first.inner_text()=='Great gerbil')
    expect(page.locator('#summary')).to_contain_text('10 types. 3 critical.')
    check('classification and satire notice are visible',page.locator('.type-note').is_visible())
    fits(page,'desktop fits')
    page.screenshot(path=str(OUT/'desktop.png'),full_page=True)
    page.locator('#kind').select_option('Species');expect(page.locator('#watch-rows tr')).to_have_count(3)
    page.locator('#kind').select_option('Coat variety');expect(page.locator('#watch-rows tr')).to_have_count(7)
    check('classification filter separates species from seven coat varieties')
    page.locator('#search').fill('black');expect(page.locator('#watch-rows tr')).to_have_count(1)
    page.locator('#watch-rows button').click()
    expect(page.locator('#dialog-title')).to_have_text('Black')
    expect(page.locator('.identity-note')).to_contain_text('black eyes')
    check('dossier links its real identity source',page.locator('.identity-note a').get_attribute('href')=='https://gerbils.co.uk/gerbil-show-standards/')
    expect(page.locator('.dossier-copy')).to_contain_text('FICTIONAL THREAT ASSESSMENT')
    check('identity and parody are separate sections')
    page.get_by_role('button',name='Reveal redacted intelligence').click()
    expect(page.locator('.redaction')).to_contain_text('Night vision')
    check('reveal shows type-specific invented intelligence')
    with page.expect_download() as event:page.locator('[data-export]').click()
    report=json.loads(Path(event.value.path()).read_text())
    check('export carries type, taxonomy, source and fiction flag',report['name']=='Black' and report['kind']=='Coat variety' and report['assessmentIsFictional'] and report['source'].startswith('https://'))
    page.screenshot(path=str(OUT/'dossier.png'),full_page=True)
    page.keyboard.press('Escape');expect(page.locator('#watch-rows button')).to_be_focused()
    check('closing dossier restores focus')
    page.locator('#search').fill('impossible type');expect(page.locator('#empty')).to_be_visible()
    page.locator('[data-action="clear"]').click();expect(page.locator('#watch-rows tr')).to_have_count(10)
    check('empty search and clear reset filters')
    page.locator('#sort').select_option('lowest');expect(page.locator('#watch-rows strong').first).to_have_text('Dove')
    page.locator('#sort').select_option('highest');expect(page.locator('#watch-rows strong').first).to_have_text('Great gerbil')
    check('sort works in both directions')
    page.locator('#level').select_option('Critical');expect(page.locator('#watch-rows tr')).to_have_count(3)
    check('threat-level filter works')
    load(page)
    page.locator('.nav [data-tab="assess"]').click()
    expect(page.locator('#assessed-type option')).to_have_count(10)
    check('reassessment selects a known type, not an individual name',page.locator('#suspect-name').count()==0)
    page.locator('#assessed-type').select_option('T-010')
    for i in range(4):page.locator(f'#factor-{i}').fill('100')
    page.locator('#assessment-form button[type="submit"]').click()
    expect(page.locator('#dialog-title')).to_have_text('Dove')
    expect(page.locator('.dossier-side .big-score')).to_contain_text('100')
    page.keyboard.press('Escape')
    expect(page.locator('#watch-rows tr')).to_have_count(10)
    expect(page.locator('#watch-rows strong').first).to_have_text('Dove')
    check('reassessment changes rank without creating a fictional breed')
    load(page)
    page.locator('.masthead [data-action="report"]').click()
    expect(page.locator('#incident-subject option')).to_have_count(10)
    page.locator('#incident-subject').select_option('T-001');page.locator('#incident-behavior').select_option('paper')
    page.locator('#incident-note').fill('<img src=x onerror=alert(1)>')
    page.locator('#incident-form button[type="submit"]').click()
    expect(page.locator('#incidents-list')).to_contain_text('<img src=x onerror=alert(1)>')
    check('incident user text is escaped',page.locator('#incidents-list img').count()==0)
    page.locator('.nav [data-tab="register"]').click()
    expect(page.locator('#spotlight-score')).to_have_text('100')
    check('incident score and featured score stay synchronized')
    page.locator('[data-action="reset"]').click();page.locator('[data-action="confirm-reset"]').click()
    expect(page.locator('#spotlight-score')).to_have_text('98')
    expect(page.locator('#register-count')).to_have_text('10')
    check('reset restores ten real types and baseline ratings')
    for width,height in [(320,568),(390,844),(768,1024)]:
        page.set_viewport_size({'width':width,'height':height});load(page);fits(page,f'{width}px register fits')
        if width==390:page.screenshot(path=str(OUT/'mobile.png'),full_page=True)
        page.locator('#watch-rows button').first.click();fits(page,f'{width}px dossier fits')
        if width==390:page.screenshot(path=str(OUT/'mobile-dossier.png'))
        page.keyboard.press('Escape')
    check('no automatic external requests',requests==[])
    check('no browser errors',errors==[])
    check('no cookies',context.cookies()==[])
    browser.close()
result={'mode':MODE,'passed':len(checks),'checks':checks,'errors':errors,'externalRequests':requests}
(OUT/'browser-results.json').write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
